# Generated by Django 3.2 on 2023-10-08 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(db_index=True, max_length=20, verbose_name='Card')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('finance', models.TextField(verbose_name='finance description')),
                ('love', models.TextField(verbose_name='love description')),
                ('day', models.TextField(verbose_name='day description')),
                ('advise', models.TextField(verbose_name='advise description')),
                ('yes_or_no', models.TextField(verbose_name='yes or no description')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Telegram ID')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('U', 'User'), ('L1', 'Magic user')], default='U', max_length=50, verbose_name='Subscription level')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='Status')),
                ('date_from', models.DateTimeField(blank=True, null=True, verbose_name='Subscription start')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Subscription end')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Price')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tarot.user')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('prediction', models.CharField(db_index=True, max_length=15, verbose_name='Prediction')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='tarot.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='tarot.user')),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
            },
        ),
    ]
