# Generated by Django 3.2 on 2023-07-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(db_index=True, max_length=40, verbose_name='Карта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('finance', models.TextField(verbose_name='Описание на финансы')),
                ('love', models.TextField(verbose_name='Описание на любовь')),
                ('day', models.TextField(verbose_name='Описание на день')),
                ('advise', models.TextField(verbose_name='Описание на совет')),
                ('triple', models.TextField(verbose_name='Описание на тройной расклад')),
                ('yes_or_no', models.TextField(verbose_name='Описание на да или нет')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Имя и фамилия')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Город')),
                ('date', models.DateTimeField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('U', 'Пользователь'), ('L1', 'Первый'), ('L2', 'Второй'), ('L3', 'Третий')], default='U', max_length=50, verbose_name='Уровень подписки')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='Статус')),
                ('date_from', models.DateTimeField(blank=True, null=True, verbose_name='Начало подписки')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Конец подписки')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tarot.user')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата предсказания')),
                ('finance_flag', models.PositiveIntegerField(verbose_name='Флаг для финансов')),
                ('love_flag', models.PositiveIntegerField(verbose_name='Флаг для любовного')),
                ('day_flag', models.PositiveIntegerField(verbose_name='Флаг для дневного')),
                ('advise_flag', models.PositiveIntegerField(verbose_name='Флаг для совета')),
                ('triple_flag', models.PositiveIntegerField(verbose_name='Флаг для тройного')),
                ('yes_or_no_flag', models.PositiveIntegerField(verbose_name='Флаг для да или нет')),
                ('card', models.ManyToManyField(related_name='predictions', to='tarot.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='tarot.user')),
            ],
            options={
                'verbose_name': 'Предсказание',
                'verbose_name_plural': 'Предсказания',
            },
        ),
    ]
