# Generated by Django 3.2 on 2023-09-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterModelOptions(
            name='prediction',
            options={'verbose_name': 'Prediction', 'verbose_name_plural': 'Predictions'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='card',
            name='advise',
            field=models.TextField(verbose_name='advise description'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='day',
            field=models.TextField(verbose_name='day description'),
        ),
        migrations.AlterField(
            model_name='card',
            name='finance',
            field=models.TextField(verbose_name='finance description'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='card',
            name='love',
            field=models.TextField(verbose_name='love description'),
        ),
        migrations.AlterField(
            model_name='card',
            name='triple',
            field=models.TextField(verbose_name='triple description'),
        ),
        migrations.AlterField(
            model_name='card',
            name='yes_or_no',
            field=models.TextField(verbose_name='yes or no description'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='advise_flag',
            field=models.PositiveIntegerField(verbose_name='advise_flag'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='day_flag',
            field=models.PositiveIntegerField(verbose_name='day_flag'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='finance_flag',
            field=models.PositiveIntegerField(verbose_name='finance_flag'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='love_flag',
            field=models.PositiveIntegerField(verbose_name='love_flag'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='triple_flag',
            field=models.PositiveIntegerField(verbose_name='triple_flag'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='yes_or_no_flag',
            field=models.PositiveIntegerField(verbose_name='yes_or_no_flag'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription end'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription start'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='role',
            field=models.CharField(choices=[('U', 'User'), ('L1', 'Magic user'), ('L2', 'Fairy user'), ('L3', 'Almighty user')], default='U', max_length=50, verbose_name='Subscription level'),
        ),
    ]
