# Generated by Django 3.2 on 2023-10-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0002_auto_20230922_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='role',
            field=models.CharField(choices=[('U', 'User'), ('L1', 'Magic user')], default='U', max_length=50, verbose_name='Subscription level'),
        ),
    ]
