# Generated by Django 3.2 on 2023-10-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0003_alter_subscription_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='triple',
        ),
    ]
